$ModLoad imuxsock
$ModLoad imklog

$KLogPermitNonKernelFacility on
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$RepeatedMsgReduction on
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

$IncludeConfig /etc/rsyslog.d/

auth,authpriv.*                  /var/log/auth.log
*.*;auth,authpriv.none           -/var/log/syslog
daemon.*                         -/var/log/daemon.log
kern.*                           -/var/log/kern.log
lpr.*                            -/var/log/lpr.log
mail.*                           -/var/log/mail.log
user.*                           -/var/log/user.log

mail.info                        -/var/log/mail.info
mail.warn                        -/var/log/mail.warn
mail.err                         /var/log/mail.err

*.=debug;\
  auth,authpriv.none;\
  news.none;mail.none            -/var/log/debug
*.=info;*.=notice;*.=warn;\
  auth,authpriv.none;\
  cron,daemon.none;\
  mail,news.none                 -/var/log/messages

*.emerg                          :omusrmsg:*
